language: go

go:
  - "1.12.5"

before_install:
  - sudo apt-get update 
  - sudo apt-get install build-essential
  - sudo apt-get install libjudy-dev

script:
  - export GO111MODULE=on
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
